# Generated by Django 4.0.2 on 2022-02-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teaches',
            new_name='Teaching',
        ),
    ]
