# Generated by Django 4.0.2 on 2022-02-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_rename_teaches_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('professor', 'module', 'semester', 'year')},
        ),
    ]
